name: Test Docker Build

# Déclenche l'action à chaque push ou pull request sur la branche principale
on:
  push:
    branches: [ "main" ] 
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest # GitHub utilise une machine virtuelle Linux

    steps:
    - name: Récupérer le code du projet
      uses: actions/checkout@v3

    - name: Tester la construction du Dockerfile
      run: docker build -t ecosort .